name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ] 
  repository_dispatch:
    types: [ cart-tests ] 
  workflow_dispatch:
  
jobs:
  dupa
